apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: node-app
  labels:
    app: node-app 
spec:
  selector:
    app: node-app 
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000 