apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app   
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sharara99/React-UI-library.git
    targetRevision: HEAD
    path: k8s/UI-App
  destination:
    server: https://kubernetes.default.svc
    namespace: node-app   
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      # ArgoCD will automatically sync when changes are detected (e.g., new image)
